### PR TITLE
Avoid jsonifying Buffers for ServiceBus and variants.

### PR DESCRIPTION
**Pull request by noodlefrenzy**
Attempted fix for https://github.com/Azure/azure-event-hubs/issues/118

### CODE REVIEW

**Comment by mbroadst** [comment]
LGTM

**Comment by ThomasAnnerel** [comment]
Just tried thuis commit.
We het followig exception:
Unhandled rejection (<{"descriptor":{"buffer":{"type":"Buffe...>, no stack trace)

https://gist.github.com/ThomasAnnerel/548307a92c84e6888b777c131c593c2f

**Comment by ThomasAnnerel** [comment]
I guys I found another problem in the servicebus policy
maxMessageSize: 10000, // Arbitrary choice

If you look at https://azure.microsoft.com/en-us/documentation/articles/service-bus-quotas/ we notice this should be 256 bytes

Kind regards
Thomas Annerel

**Comment by mbroadst** [comment]
@ThomasAnnerel sorry you're still having trouble! I'll defer to @noodlefrenzy on the actual ServiceBus related stuff here, but it looks like  you're correct on that constant - would you be willing to put together a PR for that?

**Pull request merged**
