### PR TITLE
 Added example for DEBUG=amqp10:client env variable

### PR DESCRIPTION
**Pull request by snobu**

### CODE REVIEW

**Comment by snobu** [comment]
Oh noes i broke the build.

image

**Comment by mbroadst** [comment]
well that's really strange, seems to be related to the secret SB/EH variables built into travis, I'm forcing a rerun to see if it was a fluke

**Comment by mbroadst** [comment]
hmm no dice, we'll have to wait for @noodlefrenzy to wake up to take a look at that since he set it up (and actually knows the contents of those env variables). They may have just expired or something silly.

**Comment by noodlefrenzy** [comment]
I don't allow forks to see those env variables (otherwise people could just submit PRs with tests that just dump the keys). I'll take a look at what would be required to disable those tests on forks - I'm fairly certain there's a travis environment variable I should be using there. In the meantime, I'll merge the PR as it looks good, thanks!

**Comment by mbroadst** [comment]
oh, duh :smile:

**Pull request merged**
